import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,freeAction,buyTicket,revealTicket,continueFeedback,choose,ensureCard,migrateSave,setIdentity,dateName,advanceNotice} from '../src/engine.js';
import {PEOPLE} from '../src/content.js';
import {LOTTERY_TICKETS,lotteryStats} from '../src/lottery.js';
function ready(){const s=createGame({background:'ordinary'},67);s.phase='events';s.notices=[];s.deferred=null;s.hooks['0-0-committee']=true;s.card={id:'original',kind:'choice',consume:true,choices:[{text:'继续',effects:{},result:'继续生活'}]};return s;}
function weekend(){const s=ready();choose(s,0);continueFeedback(s);assert.equal(s.freeTime.scheduled,true);return s;}
test('weekend opens automatically between monthly events, and skip does not repeat or advance time',()=>{const s=weekend(),balance=s.balance,tick=s.calendarTick;assert.equal(s.eventSlot,1);assert.equal(s.card.kind,'free');assert.ok(s.card.title.startsWith('周末'));assert.ok(freeAction(s,'skip'));assert.equal(s.freeTime,null);assert.equal(s.card.kind,'choice');assert.equal(s.month,0);assert.equal(s.eventSlot,1);assert.equal(s.calendarTick,tick);assert.equal(s.balance,balance);choose(s,0);continueFeedback(s);assert.equal(s.month,1);assert.equal(s.eventSlot,0);assert.equal(s.freeTime,null);while(s.card?.kind==='notice')advanceNotice(s);choose(s,0);continueFeedback(s);assert.equal(s.month,1);assert.equal(s.freeTime.scheduled,true);});
test('weekend activity pays once, restores regular events and does not settle another monthly allowance',()=>{const s=weekend(),balance=s.balance,energy=s.energy,tick=s.calendarTick;freeAction(s,'work');assert.equal(s.balance,balance+100);assert.equal(s.energy,energy-10);assert.equal(freeAction(s,'work'),false);continueFeedback(s);assert.equal(s.card.kind,'choice');assert.equal(s.calendarTick,tick);assert.equal(s.eventSlot,1);assert.equal(s.freeTime,null);assert.equal(s.traits['兼职经历'],1);assert.ok(!s.history.some(h=>h.tag==='兼职经历'));});
test('weekend lottery browsing can cancel, saved ticket restores, and no double payout or extra weekend',()=>{let s=weekend();const balance=s.balance,tick=s.calendarTick;freeAction(s,'lottery');const rng=s.rng;freeAction(s,'back');assert.equal(s.card.kind,'free');assert.equal(s.rng,rng);assert.equal(s.balance,balance);freeAction(s,'lottery');assert.ok(buyTicket(s,'pocket'));assert.equal(buyTicket(s,'grand'),false);s=migrateSave(JSON.parse(JSON.stringify(s)));const prize=s.lotteryTransactions[0].prize;assert.ok(revealTicket(s));assert.equal(revealTicket(s),false);continueFeedback(s);assert.equal(s.balance,balance-10+prize);assert.equal(s.calendarTick,tick);assert.equal(s.eventSlot,1);assert.equal(s.card.kind,'choice');assert.equal(s.freeTime,null);});
test('six ticket denominations have increasing reachable jackpot odds and affordable purchase gates',()=>{assert.deepEqual(LOTTERY_TICKETS.map(t=>t.price),[10,20,50,100,500,1000]);const chances=LOTTERY_TICKETS.map(t=>lotteryStats(t).jackpotChance);assert.ok(chances.every((p,i)=>p>0&&(!i||p>chances[i-1])));const s=weekend();freeAction(s,'lottery');s.balance=4;const rng=s.rng;assert.equal(buyTicket(s,'pocket'),false);assert.equal(s.rng,rng);s.balance=10;assert.equal(buyTicket(s,'grand'),false);assert.ok(buyTicket(s,'pocket'));assert.equal(s.balance,0);});
test('scheduled weekend jackpot can continue without re-opening the same weekend',()=>{const s=weekend();freeAction(s,'lottery');buyTicket(s,'small');s.lotteryTransactions[0].prize=10000000;revealTicket(s);continueFeedback(s);assert.equal(s.card.id,'jackpot');choose(s,1);continueFeedback(s);assert.equal(s.card.kind,'choice');assert.equal(s.eventSlot,1);assert.equal(s.freeTime,null);assert.ok(s.balance>10000000);});
test('old in-progress external ticket still restores its suspended event and deferred milestone',()=>{const s=ready(),card=structuredClone(s.card);s.freeTime={external:true,consume:false,returnCard:card,returnDeferred:'target'};s.card={kind:'lottery'};buyTicket(s,'small');s.lotteryTransactions[0].prize=10000000;const restored=migrateSave(JSON.parse(JSON.stringify(s)));revealTicket(restored);continueFeedback(restored);choose(restored,1);continueFeedback(restored);assert.deepEqual(restored.card,card);assert.equal(restored.deferred,'target');assert.equal(restored.freeTime,null);assert.equal(restored.eventSlot,0);});
test('date and gift require current partner and affordability; memories belong to that partner',()=>{const s=weekend();assert.equal(freeAction(s,'date'),false);s.relationship={person:PEOPLE[0],stage:'dating'};s.balance=50;assert.equal(freeAction(s,'gift'),false);assert.equal(s.balance,50);s.balance=200;assert.ok(freeAction(s,'gift'));assert.equal(s.balance,80);assert.equal(s.relationship.memories,1);assert.ok(s.relationship.intimacy>55);continueFeedback(s);s.relationship=null;s.card=null;s.month=1;s.eventSlot=1;ensureCard(s);assert.equal(freeAction(s,'date'),false);});
test('vacation appears once between terms and study carries forward without rewriting grades',()=>{const s=ready();s.sem=1;s.month=0;s.phase='start';s.card=null;s.grades=[{sem:0,grade:90,comp:80}];ensureCard(s);assert.equal(s.freeTime.holiday,'寒假');assert.equal(dateName(s),'寒假 · 一月—二月');freeAction(s,'study');const prep=s.study;continueFeedback(s);assert.equal(s.card.kind,'focus');assert.equal(s.study,prep);assert.equal(s.grades[0].grade,90);s.card=null;ensureCard(s);assert.equal(s.freeTime,null);});
test('scheduled weekends yield to entrance-exam milestones and preserve semester choices',()=>{const s=ready();s.sem=6;s.month=3;s.eventSlot=1;s.route='exam';s.policy.published=true;s.card=null;ensureCard(s);assert.equal(s.card.kind,'quiz');assert.equal(s.freeTime,null);assert.equal(s.hooks['weekend-6-3'],undefined);});
test('gender sets future partner gender in new and migrated saves while preserving an existing relationship',()=>{for(const gender of ['male','female']){const s=createGame({gender,romancePreference:'any'},5),opposite=gender==='male'?'female':'male';assert.equal(s.romancePreference,opposite);s.romancePreference='any';s.candidate=PEOPLE.find(p=>p.gender===gender);s.relationship={person:PEOPLE[0],stage:'dating'};const restored=migrateSave(s);assert.equal(restored.romancePreference,opposite);assert.equal(restored.candidate,null);assert.equal(restored.relationship.person.name,PEOPLE[0].name);setIdentity(restored,gender==='male'?'female':'male');assert.equal(restored.romancePreference,gender);}});
