const op=(text,effects,result,extra={})=>({text,effects,result,...extra});
const link=(id,extra={})=>({id,after:1,expires:8,...extra});
const scene=(id,title,text,choices,extra={})=>({id,title,text,choices,group:'common',category:'project',storyScope:'run',repeat:false,weight:1,minSem:1,maxSem:7,...extra});
const success=(text,effects,followUp,setFlags)=>({text,effects,followUp,setFlags});
export const EXTENDED_STORIES=[
  scene('attendance-hole','缺课与作业，正在累积','老师提醒几份作业还没有提交。你现在可以补上，也可以继续把问题推后。',[
    op('补齐缺交内容，核对自己漏掉的课',{study:5,energy:-8},'你完成了缺交内容，开始恢复规律安排。'),
    op('继续缺课，不交这两次作业',{study:-3,absence:2,energy:12,mood:2},'休息时间增加了，缺课与未交作业也进入本学期记录。'),
    op('向老师说明困难，先完成最重要的部分',{study:3,energy:-5,mood:3},'你没有假装都能做到，也没有继续失联。'),
  ],{category:'study',minSem:0,maxSem:13,repeat:true,cooldown:3}),
  scene('attendance-warning','连续缺课之后，老师找你谈了一次','这学期已经有多次缺课或未交作业。期末前还可以补救，但一次突击不能抹去全部问题。',[
    op('从现在起按时上课，补一段系统复习',{study:7,energy:-10},'你认真补回基础，早先缺课仍会反映在本学期成绩里。'),
    op('请同学一起整理课程，完成可补交内容',{study:5,energy:-8,tags:['学业互助']},'有人帮助你重新进入节奏，你也开始承担自己的作业。'),
    op('仍然不处理，再拖两次作业',{study:-4,absence:2,energy:10,mood:-4},'问题继续累积，可能需要期末后的课程补救。'),
  ],{category:'study',minSem:0,maxSem:13,minMissed:2,repeat:true,cooldown:2}),
  scene('competition-entry','队伍还缺一个人','同学邀请你参加{competition}。报名只是开始，之后还会有分工、修改和交付。',[
    op('确定分工，再承担自己的一部分',{energy:-5,study:2},'你加入队伍，约好了可完成的范围。',{setFlags:{competitionActive:true,competitionPrepared:true},followUp:link('competition-team',{clearFlags:['competitionActive']})}),
    op('先做一个小样，确认方案可行',{energy:-8,study:4},'小样发现了几个问题，大家决定缩小题目。',{setFlags:{competitionActive:true,competitionPrepared:true},followUp:link('competition-team',{clearFlags:['competitionActive']})}),
    op('不占报名名额，帮他们联系合适的同学',{mood:3},'队伍继续出发，你没有把自己塞进另一项长期任务。',{freeTimeGain:1}),
  ],{notFlags:['competitionActive'],duration:2}),
  scene('competition-team','交付前，队友的那一部分还是空白','离提交{competition}作品还有时间，但一位队友没有完成约定的内容。群里突然安静得很整齐。',[
    op('把任务拆小，和队友一起完成关键部分',{energy:-12,study:4},'你们重新确认分工，决定先交一个完整版本。',{setFlags:{competitionCooperation:true},followUp:link('competition-final',{clearFlags:['competitionActive']})}),
    op('缩减功能，写清楚目前能证明的结果',{energy:-7,study:3},'作品规模小了，内容却更加可靠。',{setFlags:{competitionHonest:true},followUp:link('competition-final',{clearFlags:['competitionActive']})}),
    op('及时退出，向老师说明已完成的部分',{energy:6,mood:-3},'你没有继续承担无法完成的承诺。比赛没有给你奖项，过程仍留下了经验。',{setFlags:{competitionActive:false}}),
  ],{followOnly:true,requiresFlags:['competitionActive'],duration:3}),
  scene('competition-final','答辩当天，老师问到了最薄弱的部分','你们站在{competition}答辩现场。评委想知道成果怎样得到，而不是 PPT 有多少动画。',[
    {text:'用实际过程和验证说明作品',effects:{energy:-4},probability:{base:.5,tags:{规律复习:.08,软件项目:.06,工程项目:.06,商业分析:.06,公共表达:.06},grade:.003},success:success('团队获得了一个奖项。你记得的还有一起赶上交付的过程。',{activity:7,mood:12,tags:['竞赛获奖']},null,{competitionActive:false}),failure:success('没有获奖，但你们收到了可以继续改进的意见。',{activity:2,mood:1},null,{competitionActive:false})},
    op('坦诚承认限制，把讨论引向下一步',{activity:3,study:2,mood:4},'评委认可你们对边界的解释。没有奖项，也不是白做。',{setFlags:{competitionActive:false}}),
    op('请擅长表达的队友主讲，自己补充细节',{activity:4,mood:5},'分工终于在现场发挥作用，你们完成了答辩。',{requiresFlags:['competitionCooperation'],setFlags:{competitionActive:false}}),
  ],{followOnly:true,requiresFlags:['competitionActive'],duration:0}),
  scene('internship-apply','暑期实习的申请回信','你申请了{internship}。对方要看一份具体作品或实践经历，也想知道你愿意做什么。',[
    {text:'准备实例，认真参加面试',effects:{energy:-8,study:2},probability:{base:.63,grade:.004,tags:{软件项目:.08,工程项目:.08,教育实习:.08,商业分析:.08,政策调研:.08}},success:success('你得到了一段实习机会，职责与报酬在开始前讲清楚。',{},link('internship-work',{clearFlags:['internshipActive']}),{internshipActive:true}),failure:success('这次未获得实习。你留下了面试反馈，之后可以补齐作品。',{study:1},null,{internshipActive:false})},
    op('选择校内短期实践，先积累一个案例',{study:4,activity:2,energy:-6},'你完成了一个小规模实践，不把它写成正式实习。',{setFlags:{internshipActive:false}}),
    op('撤回申请，保留已经安排好的假期',{mood:4,energy:6},'你告诉对方自己的安排，没有留下一个失联的承诺。',{setFlags:{internshipActive:false}}),
  ],{followOnly:true,minSem:2,maxSem:12,duration:0}),
  scene('internship-work','第一次交付，需求在最后一天变了','{internship}的负责人改了需求。你有一个初稿，也有一个快到的截止日期。',[
    op('确认优先级，交付最必要的部分',{energy:-12,study:4},'你明确了能完成的范围，对方愿意继续让你承担工作。',{setFlags:{internshipReliable:true},followUp:link('internship-end',{clearFlags:['internshipActive']})}),
    op('请带教一起评估，约定延期与反馈',{energy:-8,study:3},'你没有自己猜需求，带教指出了真正需要修改的内容。',{setFlags:{internshipMentored:true},followUp:link('internship-end',{clearFlags:['internshipActive']})}),
    op('只交原稿，之后认真处理退回意见',{energy:-4,mood:-4},'原稿被退回，带教提醒你：遇到变化需要先沟通。',{setFlags:{internshipFrustrated:true},followUp:link('internship-end',{clearFlags:['internshipActive']})}),
  ],{followOnly:true,requiresFlags:['internshipActive'],minSem:2,maxSem:13,duration:4}),
  scene('internship-end','实习结束，怎样留下这一段经历','最后一周，你需要交接材料。{internship}留下的实际工作，会成为以后面试里可以讲的事情。',[
    op('整理交接与复盘，向带教确认贡献',{balance:1200,energy:-5,mood:8,tags:['实习经历']},'报酬 ¥1,200 到账，你完成了交接，也得到一份真实的实践记录。',{setFlags:{internshipActive:false,internshipFinished:true}}),
    op('先完成交接，和合作同事保持联系',{balance:1200,mood:6,tags:['实习经历','校友联系']},'报酬到账，你留下了工作记录与可以继续联系的人。',{setFlags:{internshipActive:false,internshipFinished:true}}),
    op('请带教核对自己的薄弱点，再结束',{balance:1200,study:3,energy:-4,tags:['实习经历']},'你没有把所有工作都写成自己的成果，知道了下一步可以补什么。',{setFlags:{internshipActive:false,internshipFinished:true}}),
  ],{followOnly:true,requiresFlags:['internshipActive'],minSem:2,maxSem:13,duration:0,variants:[{flag:'internshipFrustrated',text:'带教提到了上次退回的初稿。最后一周，你还有机会把交接和复盘认真做完。'}]}),
  scene('policy-near-line','距离推免参考线，还差几名','本局参考线是{policyLine}。当前第{currentRank}名，距离并不遥远，但时间不能同时给每件事。',[
    op('分析薄弱课程，连续投入一段复习',{study:7,energy:-12},'你把模糊的焦虑换成了具体复习安排。下次排名仍取决于期末结算。',{duration:3}),
    op('选择一次有真实产出的实践',{study:2,activity:4,energy:-8},'你没有为了综测随便报名，留下了一项完成的工作。'),
    op('和老师核对规则，再决定升学准备',{study:2,mood:7},'你弄清楚了门槛，也保留了考研与就业准备的空间。',{duration:1}),
  ],{minSem:2,maxSem:5,policyBand:'near',category:'study'}),
  scene('policy-leading','参考线以内，也需要继续走完课程','你目前达到{policyLine}，资格还要等大三结束结算。有人说“已经稳了”，老师说“先把作业交了”。',[
    op('保持规律，把主要课程完成',{study:5,energy:-8,tags:['规律复习']},'你继续做该做的事，没有把参考线当作录取通知书。'),
    op('留出一点时间帮同学讨论问题',{study:2,activity:2,mood:5,tags:['学业互助']},'讨论也让你发现了自己遗漏的知识。'),
    op('适当休整，保留正常课堂安排',{energy:13,mood:8},'你没有继续加码，也没有放弃上课。'),
  ],{minSem:2,maxSem:5,policyBand:'leading',category:'study'}),
  scene('budget-device','设备坏了，作业还要交','你的设备开始随机罢工。维修、新购与借用都能解决一部分问题，预算却不同。',[
    op('先维修，保留可以继续用的设备',{balance:-420,study:2},'设备恢复了工作，你也留住了一部分预算。'),
    op('买满足课程要求的基础设备',{balance:-1600,study:3,mood:4},'你按真正的需求采购，没有把参数排名当作课程成绩。'),
    op('借用机房和同学设备，错峰完成作业',{energy:-8,study:2},'你需要协调时间，但没有因为缺钱直接放弃交作业。'),
  ],{category:'life',minSem:0}),
  scene('budget-trip','朋友约一场说走就走的旅行','群里路线已经排好，预算却还没有写。你看了一眼余额，决定先问清楚。',[
    op('约定人均预算，再一起出发',{balance:-580,mood:20,energy:4},'大家按商量好的预算完成旅行，回来后还有正常生活的钱。'),
    op('改成附近的一日游',{balance:-90,mood:12,energy:6},'目的地近了，聊天和风景仍然是真的。'),
    op('这次不去，找一天在校园里见面',{mood:5,energy:4},'你认真说明了自己的安排，朋友没有因为距离少走了几公里就消失。'),
  ],{category:'social'}),
  scene('budget-course','一份“保过”的课程广告','广告写得比你的期末答卷还自信。你需要准备考试，但也需要判断这笔钱究竟买到了什么。',[
    op('试听并核对内容，再选小班辅导',{balance:-260,study:5,energy:-6},'你选择了针对薄弱点的辅导，成绩仍需要自己完成。'),
    op('找免费资料，和同学互相讲解',{study:4,energy:-9,tags:['学业互助']},'你们用实际题目检验资料，没有花钱购买一句保证。'),
    op('先问老师课程要求，避免盲目购买',{study:2,mood:4},'你得到了一份明确的准备清单，广告没有替你做决定。'),
  ],{category:'study',minSem:0}),
  scene('state-social-pressure','群里所有人，好像都比你有进度','比赛、证书、实习的消息同时刷过。你看着自己的安排，觉得怎么选都慢了一步。',[
    op('和信任的人聊聊，重新排一个小目标',{mood:16,energy:5},'别人的截图不是你的全局。你把下周能做的事写清楚。'),
    op('关掉群消息，按自己的节奏完成一件事',{study:3,mood:8,energy:-3},'一件实际完成的事，比继续刷新更让你踏实。'),
    op('给自己留一段休息，不立刻追赶',{mood:11,energy:12},'你暂时停止比较，之后仍可以重新安排。'),
  ],{category:'life',maxMood:45,minSem:0,duration:1}),
  scene('aero-shared-language','航宇工科与精品文科，共用一页 PPT','技术组写了十行缩写，文科组问了十个“它会影响谁”。老师说，这两种问题都得回答。',[
    op('把技术过程写成人能理解的说明',{study:3,activity:2,energy:-6,tags:['公共表达']},'你们补齐了技术与使用者之间的解释。'),
    op('请对方讲一个例子，再一起改稿',{study:2,activity:2,mood:4},'缩写少了，方案的用途反而更加清楚。'),
    op('保留两份附件，正文只讲共同结论',{study:2,energy:-3},'各自的专业依据仍然存在，也有了可以一起展示的版本。'),
  ],{group:'school',school:'aero'}),
  scene('normal-open-class','京师公开课，学生提了一个意外问题','试讲已经排练过三遍，台下却问了一个教案没有准备的问题。',[
    op('承认需要查证，和学生一起寻找依据',{study:4,mood:4,energy:-5,tags:['学业互助']},'你没有用权威遮住问题，课后补上了答案。'),
    op('把问题留作讨论，先完成教学重点',{activity:2,study:2,energy:-4},'课堂保持了节奏，也没有丢掉那个问题。'),
    op('请同学扮演学生，再练一次回答',{study:3,energy:-5},'这次排练终于不只有背稿。'),
  ],{group:'school',school:'normal',category:'study'}),
  scene('finance-valuation','华人的模拟投资赛，群里有人宣布财务自由','账面收益截图传遍宿舍，你打开说明书才发现比赛只进行了一周。',[
    op('核对风险，把短期收益和结论分开',{study:4,activity:2,energy:-5,tags:['深度阅读']},'你讲清楚了时间和风险，没有用一张截图证明未来。'),
    op('做一次模拟复盘，比较不同选择',{study:3,energy:-4},'没有真实拿余额去下注，你仍学到了一些东西。'),
    op('当成校园趣事听听，正常吃食堂',{mood:7,energy:3},'群里继续热闹，你的晚饭还是按正常预算安排。'),
  ],{group:'school',school:'finance',category:'study'}),
  scene('major-cs-review','代码评审：能跑，不代表下一位能维护','项目演示通过了，队友却说自己看不懂你写的函数。',[
    op('补接口说明，再和队友一起改结构',{study:5,energy:-8},'你减少了隐藏假设，下一次合作顺利了些。'),
    op('先写复现步骤，明确目前的限制',{study:3,energy:-5},'问题终于可以讨论，不再靠猜。'),
    op('请队友演示卡在哪里，再针对性修改',{study:4,mood:3,energy:-6},'你发现了使用者与作者看到的不是同一个问题。'),
  ],{group:'major',major:'cs',category:'study'}),
  scene('major-humanities-fieldwork','精品文科调研：问卷很满，结论很空','你们收回了不少问卷，老师问的是“这些人为什么这样回答”。',[
    op('补访谈，核对没有被问卷解释的部分',{study:4,activity:2,energy:-7},'你把回答背后的条件补进了报告。'),
    op('缩小结论范围，说明样本限制',{study:3,energy:-4},'报告更谨慎，也更经得起追问。'),
    op('请工科同学一起核对统计和表述',{study:3,mood:4,energy:-5,tags:['跨校社交']},'你们没有用图表替代解释，也没有用解释代替数据。'),
  ],{group:'major',major:'humanities',category:'study'}),
  scene('major-aero-test','风洞实验，结果与预计差了一截','漂亮的曲线没有出现，仪器和模型都需要重新检查。',[
    op('先排查测量条件，保留异常数据',{study:5,energy:-8},'你发现了一处条件设置错误，原始数据仍可追溯。'),
    op('和同组比较方法，明确变量差异',{study:4,energy:-6,mood:2},'问题没有立即消失，排查却有了方向。'),
    op('按现有结果写局限，约下次验证',{study:3,energy:-4},'报告诚实记录了失败与下一步。'),
  ],{group:'major',major:'aerospace',category:'study'}),
  scene('major-mechanical-fit','零件能装上，拆不下来','装配实验的作品站得很稳，老师说稳定和不可拆卸不是同一个要求。',[
    op('重新核对公差，修正关键配合',{study:5,energy:-8},'你们让作品按要求工作，重新理解了“差一点”。'),
    op('做装配记录，和同组讨论工艺顺序',{study:4,energy:-6},'下次不必先装上再祈祷。'),
    op('保留样件作为问题案例，补充设计说明',{study:3,energy:-4},'失败的样件也能清楚说明设计需要改哪里。'),
  ],{group:'major',major:'mechanical',category:'study'}),
  scene('major-language-context','译文每句话都对，读起来却不对','你把原文逐句译完，同学说作者的语气好像换了个人。',[
    op('回到上下文，统一语气和术语',{study:5,energy:-8},'你不再只比较单词，也比较作者想怎样说话。'),
    op('互换译稿，讨论读者会怎样理解',{study:4,mood:3,energy:-6},'不同意见让译文有了更清楚的选择依据。'),
    op('保留两种译法，并说明各自取舍',{study:3,energy:-4},'你给出了可以讨论的方案。'),
  ],{group:'major',major:'language',category:'study'}),
  scene('major-education-observation','教育见习，课堂观察表快写满了','你记录了很多行为，带教问你：哪些是观察，哪些是自己的判断？',[
    op('把事实与解释分栏，再核对具体情境',{study:5,energy:-7},'你知道了记录越多不等于看得越准。'),
    op('和带教讨论两个典型片段',{study:4,energy:-5,mood:3},'具体片段比一句“学生不认真”更能帮助改进。'),
    op('重看课堂记录，补上自己的不确定处',{study:3,energy:-4},'你留下了可以继续核对的问题。'),
  ],{group:'major',major:'education',category:'study'}),
  scene('major-psychology-ethics','心理学作业：朋友愿意接受“测试”','你想做课程练习，朋友问结果是不是就能说明自己是什么样的人。',[
    op('说明用途和局限，确认知情同意',{study:5,energy:-6},'你把课程练习与专业判断的边界说清楚。'),
    op('改用匿名课堂案例，先练分析方法',{study:4,energy:-5},'作业继续推进，没有把朋友变成一个标签。'),
    op('请老师确认方法，再决定是否收集资料',{study:3,mood:3,energy:-4},'你先补齐了方法上的疑问。'),
  ],{group:'major',major:'psychology',category:'study'}),
  scene('major-finance-assumptions','估值表很好看，关键假设却没人检查','模型算到了小数点后两位，未来增长率却来自一句“应该会涨”。',[
    op('做不同情景，检验结论怎样变化',{study:5,energy:-7},'你看见了假设如何决定结果。'),
    op('找依据重新设定假设，写清不确定性',{study:4,energy:-6},'模型有了可追溯的输入。'),
    op('缩小报告范围，只回答能支持的问题',{study:3,energy:-4},'报告不再用精确数字掩盖未知。'),
  ],{group:'major',major:'finance',category:'study'}),
  scene('major-accounting-reconcile','对账，差额只有七块五','同学说差得很少，老师说差额大小与能否解释是两回事。',[
    op('核对来源和时间口径，逐项追踪',{study:5,energy:-7},'你找到了跨期记录的问题。'),
    op('和同学分头核对，互相复查',{study:4,mood:3,energy:-6},'复查发现了原先都忽略的一张凭证。'),
    op('保留差异说明，再请老师确认处理',{study:3,energy:-4},'你没有直接把数字改到相等。'),
  ],{group:'major',major:'accounting',category:'study'}),
];

export const STORY_TOPICS={
  cs:['校园应用开发赛','软件与数据岗位实习'],aerospace:['飞行器方案设计赛','工程验证与技术资料实习'],mechanical:['机械设计实践赛','设计与制造岗位实习'],humanities:['公共议题调研赛','调研与公共事务实习'],education:['教学方案设计赛','教学与课程助理实习'],language:['翻译与传播作品赛','内容与语言服务实习'],psychology:['心理学研究设计赛','研究与用户调研实习'],finance:['商业案例分析赛','金融研究与业务助理实习'],accounting:['财会案例分析赛','财务与审计助理实习'],
};
