// Conditional episodes remain pool entries. Follow-ups are selected by the runtime,
// never a fixed four-year story, and every ordinary scene has three authored actions.
const op=(text,effects,result,extra={})=>({text,effects,result,...extra});
const risk=(text,effects,base,success,failure,extra={})=>({text,effects,probability:{base,energy:.001,mood:.001},success,failure,...extra});
const follow=(id,after=1,extra={})=>({id,after,expires:8,...extra});
const event=(id,group,title,text,choices,extra={})=>({id,group,title,text,choices,weight:1,category:group==='romance'?'social':'project',storyScope:group==='romance'?'relationship':'cadre',cooldown:4,repeat:true,...extra});
const duty=(id,title,text,choices,roles)=>event(id,'cadre',title,text,choices,{cadre:true,roles});
const love=(id,title,text,choices,extra={})=>event(id,'romance',title,text,choices,{dating:true,...extra});
export const STORY_EVENTS=[
  event('cadre-first','cadre','第一次以{role}的身份开会','你负责{duty}。有人递来去年的流程，有人提醒你：群里说“收到”，不代表真的会做。',[
    op('列出分工和时间节点，再发给大家确认',{energy:-3},'你建立了清楚的分工，第一次实际事务很快就会到来。',{setFlags:{organized:true},followUp:follow('$cadreTask',1)}),
    op('先收集同学最关心的事情',{energy:-2,mood:2},'你记下了几个具体需求，准备从真正的问题开始。',{setFlags:{consulted:true},followUp:follow('$cadreTask',1)}),
    op('找一位搭档，约好互相提醒',{mood:3},'你没有把所有事扛在自己身上，也明确了自己仍要负责的部分。',{setFlags:{helper:true},followUp:follow('$cadreTask',1)}),
  ],{cadre:true,followOnly:true,duration:0}),
  duty('cadre-homework','学习委员与四份未交作业','截止时间临近，四位同学还没有提交。有人真的没弄懂，有人只是忘了。',[
    op('分别联系，组织一次小范围答疑',{energy:-8,study:3,activity:2},'你们把不会的题讲清楚，也约定了补交时间。',{cadreEffect:2,setFlags:{supported:true},followUp:follow('cadre-response')}),
    op('请老师确认补交规则，再统一通知',{energy:-4,activity:1},'规则先说清，大家各自承担自己的作业。',{cadreEffect:1,setFlags:{ruleFirst:true},followUp:follow('cadre-response')}),
    op('发最后一次提醒，然后如实汇总',{energy:-2},'你完成了汇总，但几位同学对处理方式有些意见。',{cadreEffect:-1,setFlags:{friction:true},followUp:follow('cadre-response')}),
  ],['class-study']),
  duty('cadre-dorm','生活委员与一张维修单','宿舍洗衣机坏了，维修单写着“已处理”，同学们的衣服却还在排队。',[
    op('核实现场，带照片去找后勤',{energy:-7,activity:2},'问题被重新受理，你留下了可以追踪的记录。',{cadreEffect:2,setFlags:{supported:true},followUp:follow('cadre-response')}),
    op('先协调附近可用的设备',{energy:-4,mood:2},'大家暂时有了替代办法，你仍保留着维修记录。',{cadreEffect:1,setFlags:{helper:true},followUp:follow('cadre-response')}),
    op('公示工单状态，让大家自行反馈',{energy:-1},'信息公开了，但等待中的同学还希望有人继续跟进。',{cadreEffect:-1,setFlags:{friction:true},followUp:follow('cadre-response')}),
  ],['class-life','union-service']),
  duty('cadre-match','文体委员的报名表','比赛需要一队人，报名表却像期末早八的教室：空得很有想象空间。',[
    op('改成体验赛，降低参与门槛',{energy:-6,activity:2},'几个原本不敢报名的同学愿意试试。',{cadreEffect:2,setFlags:{supported:true},followUp:follow('cadre-response')}),
    op('请爱运动的同学帮忙组队',{energy:-4,activity:1},'你找到了合适的队长，不必自己承担所有训练。',{cadreEffect:1,setFlags:{helper:true},followUp:follow('cadre-response')}),
    op('向组织方说明人数不足，申请缩小规模',{energy:-2},'活动规模调整了，几位同学有些遗憾，但没有被强拉上场。',{cadreEffect:0,setFlags:{ruleFirst:true},followUp:follow('cadre-response')}),
  ],['class-culture','year-culture','union-culture']),
  duty('cadre-feedback','班长与互相矛盾的意见','有人希望班会短一点，有人希望多讨论一点。群里唯一一致的意见是“你看着办”。',[
    op('先投票，再把少数意见留下',{energy:-6,activity:2},'你没有假装所有人都满意，安排却更容易被理解。',{cadreEffect:2,setFlags:{supported:true},followUp:follow('cadre-response')}),
    op('把必要事务和自由讨论分开',{energy:-4,activity:1},'大家可以办完正事后自行决定是否留下。',{cadreEffect:1,setFlags:{organized:true},followUp:follow('cadre-response')}),
    op('采用上次的安排，事后收集反馈',{energy:-2},'流程顺利走完，一些原本的问题仍留到了下次。',{cadreEffect:-1,setFlags:{friction:true},followUp:follow('cadre-response')}),
  ],['class-leader']),
  duty('cadre-cross','大班委与三种表格版本','不同班级交来的材料格式各不相同。你打开第三份时，开始理解为什么有人害怕表格。',[
    op('制作统一模板，请各班核对',{energy:-8,activity:2},'大家按模板补齐信息，汇总终于有了共同语言。',{cadreEffect:2,setFlags:{organized:true},followUp:follow('cadre-response')}),
    op('邀请各班联络人一起整理',{energy:-5,activity:2},'你们把错误当场核对，建立了下一次合作的联系。',{cadreEffect:2,setFlags:{helper:true},followUp:follow('cadre-response')}),
    op('只合并已确认的信息，说明缺项',{energy:-3,activity:1},'材料没有凭空补齐，缺项和责任也记录清楚。',{cadreEffect:1,setFlags:{ruleFirst:true},followUp:follow('cadre-response')}),
  ],['year-leader','year-study']),
  duty('cadre-stage','学生会活动前的临时变动','嘉宾晚到，场地时间却不会延长。你负责的环节需要调整，其他部门也在等消息。',[
    op('和各部门确认，把互动环节提前',{energy:-8,activity:2},'活动没有停在等待里，合作部门记住了你的及时沟通。',{cadreEffect:2,setFlags:{organized:true},followUp:follow('cadre-response')}),
    op('请搭档负责现场，自己联系嘉宾',{energy:-6,activity:2},'你们分开处理两件事，终于赶上了后半场。',{cadreEffect:2,setFlags:{helper:true},followUp:follow('cadre-response')}),
    op('缩短议程，向参与者说明原因',{energy:-3,activity:1},'内容减少了，但大家没有被毫无解释地晾着。',{cadreEffect:1,setFlags:{ruleFirst:true},followUp:follow('cadre-response')}),
  ],['union-study','union-head','union-president']),
  event('cadre-response','cadre','上次的事务有了回音','有人在走廊里叫住{role}。上次的处理没有随着群消息翻页而消失。',[
    op('听完反馈，明确下次需要改的地方',{energy:-3,activity:1},'你记下了具体意见。有些同学开始愿意主动配合。',{cadreEffect:1,setFlags:{friction:false}}),
    op('邀请同学参与下一次组织',{energy:-2,mood:3},'对方看到了幕后工作，也提出了一个更省力的办法。',{cadreEffect:1,setFlags:{helper:true}}),
    op('说明自己的职责边界，保留公开反馈渠道',{mood:1},'你没有承诺解决所有事情，大家至少知道了该找谁。',{setFlags:{ruleFirst:true}}),
  ],{cadre:true,followOnly:true,duration:0,variants:[{flag:'friction',text:'有人说，上次的处理让自己有些不舒服。你们需要把规则与难处讲清楚。'},{flag:'supported',text:'上次得到帮助的同学主动向你道谢，还问下次能不能帮忙。'},{flag:'helper',text:'上次一起办事的搭档找到你，提议把分工沿用到下次。'}]}),
  event('cadre-fairness','cadre','评优之前的一次私聊','熟悉的同学希望你在汇总意见时“帮忙照顾一下”。你知道，其他人也在认真准备材料。',[
    op('按公开规则处理，帮对方核对材料',{energy:-5,activity:2},'你提供了实际帮助，也守住了评选的规则。',{cadreEffect:2,setFlags:{fair:true}}),
    op('请另一位负责人复核，避免自己单独判断',{energy:-3,activity:1},'你让流程多了一次核对，熟人关系没有替代规则。',{cadreEffect:1,setFlags:{fair:true}}),
    op('回避这份材料，说明自己和对方熟悉',{energy:-1},'你退出了相关判断，但需要完成剩余的交接。',{cadreEffect:0,setFlags:{boundaries:true}}),
  ],{cadre:true}),
  event('cadre-date-clash','cadre','学生工作撞上约定','材料临时需要修改，而你已经和{partner}约好了见面。两件事都有人在等。',[
    op('提前说明冲突，完成必要工作后再见面',{energy:-7,activity:1,intimacy:2},'等待被解释清楚。你们调整了约会时间。',{cadreEffect:1,setFlags:{communicated:true}}),
    op('和搭档交接，再按约定去见面',{energy:-3,intimacy:4},'搭档接手了能处理的部分，你也约好了之后补上自己的工作。',{cadreEffect:1,requiresFlags:['helper']}),
    op('先办完事务，晚点再回复对象',{energy:-5,activity:2,intimacy:-12},'事务完成了，对方却不知道为什么被晾着。',{cadreEffect:1,relationshipFlags:{missed:true},followUp:follow('love-missed',1,{scope:'relationship'})}),
  ],{cadre:true,dating:true}),
  love('love-plan','约定一个属于两个人的周末','{partner}提议一起去看一场展览。你翻了翻安排，发现这个周末并不宽裕。',[
    op('答应一起去，认真留出时间',{intimacy:4},'你们定好了时间。这次约定会在后面继续。',{setFlags:{promised:true},followUp:follow('love-rain')}),
    op('说明最近的安排，改约一个轻松的晚上',{intimacy:3},'你们选择了更适合彼此的安排。',{setFlags:{communicated:true},followUp:follow('love-evening')}),
    op('这次不约出门，约好通话聊聊近况',{intimacy:2,mood:2},'对方知道你并不是随口敷衍。',{setFlags:{communicated:true}}),
  ]),
  love('love-rain','约会当天突然下雨','你还记得上次和{partner}的约定。出门时，雨比天气预报认真得多。',[
    op('买把伞，换成室内展览',{balance:-60,intimacy:7,energy:-3},'计划变了，约定没有落空。你们还发现了一家小书店。',{setFlags:{promised:false,sharedDay:true},effectsMemory:true}),
    op('商量换成校园里的一次散步',{intimacy:5,mood:3},'你们等雨小一些再出门，快乐并不需要照原计划发生。',{setFlags:{promised:false,sharedDay:true}}),
    op('临时取消，忘了及时说明',{intimacy:-14,mood:-2},'对方等了一会儿才知道你不会来。这件事需要后面认真解释。',{setFlags:{promised:false,missed:true},followUp:follow('love-missed')}),
  ],{followOnly:true}),
  love('love-evening','晚饭后一起走一段','你们按照上次商量的时间见面。{partner}带来了最近想说的一件小事。',[
    op('收起手机，认真听对方讲完',{intimacy:7,mood:5},'你记住了一件对方在意的事，也分享了自己的近况。',{setFlags:{listened:true}}),
    op('带点小零食，一边走一边聊',{balance:-25,intimacy:5,mood:4},'普通的晚上留下了共同的记忆。',{setFlags:{sharedDay:true}}),
    op('提前说明今天有点累，约好早点休息',{energy:6,intimacy:2},'你们没有把疲惫当作冷淡，见面短一些也很好。',{setFlags:{communicated:true}}),
  ],{followOnly:true}),
  love('love-missed','上次没有等到你','{partner}提起了上次的失约。问题不是那一天去了哪里，而是等待时一直没有消息。',[
    op('承认失约，商量下次如何及时联系',{energy:-3,intimacy:8},'你们明确了沟通方式，修复从具体行动开始。',{setFlags:{missed:false,communicated:true}}),
    op('把事情解释清楚，也听听对方的感受',{intimacy:5,mood:1},'你没有只讲自己的难处，对方愿意继续沟通。',{setFlags:{missed:false,listened:true}}),
    op('觉得只是小事，不想继续讨论',{intimacy:-12},'对方不再争论，却明显减少了分享。',{setFlags:{dismissed:true}}),
  ],{followOnly:true,requiresFlags:['missed'],duration:0}),
  love('love-budget','两个人的周末预算','{partner}发来几个去处。你看了看余额，觉得这次也许需要先商量预算。',[
    op('选一项付得起的活动，提前讲清预算',{balance:-80,intimacy:5,mood:5},'你们按预算安排了一个开心的下午。',{setFlags:{budgetTalk:true}}),
    op('把昂贵行程换成校园散步',{intimacy:5,mood:3},'对方在意的是一起相处，你们找到了更轻松的方式。',{setFlags:{budgetTalk:true}}),
    op('花一笔钱去一直想去的地方',{balance:-280,intimacy:6,energy:-4},'这次很难忘，也意味着最近需要控制其他开销。',{setFlags:{sharedDay:true}}),
  ],{category:'life'}),
  love('love-study-together','一起复习的约定','你们的考试时间很接近。{partner}提议找个安静的位置，各自复习。',[
    op('各自学习，休息时互相提问',{study:5,energy:-6,intimacy:5},'你们没有一直聊天，也没有把陪伴挤出考试周。',{setFlags:{sharedGoal:true}}),
    op('先讲清需要独自准备，晚点再见面',{study:4,energy:-4,intimacy:1},'你说明了安排，对方不必猜测你的沉默。',{setFlags:{communicated:true}}),
    op('放下这次复习，专心陪对方聊天',{study:-1,mood:8,intimacy:6},'相处很轻松，但今天的学习安排需要另找时间。',{setFlags:{sharedDay:true}}),
  ]),
  love('love-anniversary','被日历提醒的一天','你们相处了一段时间。{partner}问，你还记不记得第一次见面时的那件事。',[
    op('一起回到那个地方，聊聊这段时间',{balance:-40,intimacy:8,mood:5},'你们发现，记得的小事比照片还多。',{setFlags:{sharedDay:true}}),
    op('写一封信，认真说出自己的感受',{intimacy:7,energy:-3},'一些平时不好意思说的话，终于被表达出来。',{setFlags:{listened:true}}),
    op('直接问对方期待怎样纪念',{intimacy:5},'你们没有猜来猜去，而是一起决定了安排。',{setFlags:{communicated:true}}),
  ],{minIntimacy:50,cooldown:9}),
  love('love-small-habit','相处中的一个小习惯','{partner}在意的一件小事，和你的习惯不太一样。你们开始意识到，喜欢不等于生活方式完全一致。',[
    op('各自说清原因，找到双方能接受的办法',{intimacy:6},'你们有了一个具体的约定，不必靠猜测相处。',{setFlags:{communicated:true}}),
    op('先尝试对方的方法，再说自己的感受',{energy:-2,intimacy:4},'你理解了对方在意的地方，也发现了自己的边界。',{setFlags:{listened:true}}),
    op('觉得对方想太多，按原来的习惯继续',{intimacy:-9},'争论暂时停了，但问题没有消失。',{setFlags:{dismissed:true}}),
  ]),
  love('love-bad-day','对方今天不太开心','{partner}说，一件认真准备的事情没有得到想要的结果。消息比平时短了很多。',[
    op('先听对方说，不急着给建议',{intimacy:7,mood:2,energy:-3},'对方松了口气，觉得自己可以先难过一会儿。',{setFlags:{listened:true}}),
    op('问清希望你陪伴还是帮忙想办法',{intimacy:6},'你们找到了此刻真正需要的支持。',{setFlags:{communicated:true}}),
    op('最近也很累，约好晚点认真聊',{energy:4,intimacy:1},'你没有许下做不到的陪伴，也给出了明确的时间。',{setFlags:{communicated:true}}),
  ]),
  love('love-friends','和彼此的朋友一起吃饭','{partner}邀请你认识几位朋友。聊天话题从课程一路拐到了谁最会赖床。',[
    op('参与聊天，也照顾不太熟悉的人',{balance:-45,intimacy:4,mood:5},'你认识了几个新面孔，也看见了对方平时的一面。',{setFlags:{sharedDay:true}}),
    op('帮忙安排一个大家都能负担的地方',{balance:-30,intimacy:4,activity:1},'聚会没有让任何人为了合群硬撑消费。',{setFlags:{budgetTalk:true}}),
    op('这次不参加，说明自己需要休息',{energy:8,intimacy:1},'你们保留了各自的社交空间。',{setFlags:{communicated:true}}),
  ]),
  love('love-stable-future','认真聊一次以后','你们越来越熟悉彼此。{partner}问，升学或工作后，你想在哪里生活。',[
    op('先说真实想法，再了解对方的计划',{intimacy:6},'你们发现有一致之处，也有需要协调的现实。',{setFlags:{futureTalk:true},followUp:follow('love-future-check',2)}),
    op('一起比较城市、学校和生活成本',{study:2,intimacy:5,energy:-3},'未来变成了可以一起讨论的具体问题。',{setFlags:{futureTalk:true},followUp:follow('love-future-check',2)}),
    op('暂时没想好，约定各自了解后再谈',{intimacy:2},'你们没有仓促承诺，留下了继续讨论的空间。',{setFlags:{futureTalk:true},followUp:follow('love-future-check',3)}),
  ],{minIntimacy:65,minSem:4}),
  love('love-future-check','计划有了一点变化','上次谈过未来之后，你们各自了解了更多信息。{partner}希望再核对一次彼此的安排。',[
    op('分享最新的选择，协商相处方式',{intimacy:6},'你们把想法更新到同一页上。未来仍不确定，但不需要独自猜测。',{setFlags:{futureTalk:true}}),
    op('承认可能异地，约定联系和见面安排',{intimacy:4,tags:['远距离相处']},'你们没有回避距离，而是讨论了可执行的办法。',{setFlags:{distancePlan:true}}),
    op('觉得谈未来太麻烦，暂时不回复',{intimacy:-10},'对方没有得到回应，开始重新考虑共同的计划。',{setFlags:{dismissed:true}}),
  ],{followOnly:true,minSem:4}),
  love('love-repair-talk','关系紧张时的一次散步','最近你们的对话常常很短。{partner}愿意出来走一走，把问题讲清楚。',[
    op('说出自己的感受，也认真听对方讲',{energy:-3,intimacy:9},'你们终于找到争执背后的原因。',{setFlags:{dismissed:false,missed:false,listened:true}}),
    op('约定一个小改变，之后再一起检验',{intimacy:6},'修复不再停留在一句“以后会注意”。',{setFlags:{repairPromise:true},followUp:follow('love-repair-check',2)}),
    op('今天不想谈，先说明需要一点时间',{intimacy:-2,energy:3},'你争取了一点冷静时间，但这段关系仍需要处理。'),
  ],{maxIntimacy:35}),
  love('love-repair-check','上次说好的小改变','{partner}提起了上次商量的改变。这次讨论里，行动比漂亮话更重要。',[
    op('回顾已经做到的部分，继续调整',{intimacy:7,energy:-2},'你们承认改变并不完美，但也看到了进展。',{setFlags:{repairPromise:false,listened:true}}),
    op('坦诚有些地方没做到，重新商量',{intimacy:3},'你没有假装一切顺利，对方愿意继续观察。',{setFlags:{repairPromise:false,communicated:true}}),
    op('觉得说过就够了，不愿再做改变',{intimacy:-14},'这次承诺没有变成行动，关系进一步冷了下来。',{setFlags:{repairPromise:false,dismissed:true}}),
  ],{followOnly:true}),
  love('love-old-promise','后来再聊那次失约','{partner}说，上次认真解释之后，自己已经轻松了不少。你们现在可以重新安排一次见面。',[
    op('提前确认时间，按约定见面',{intimacy:6,mood:3},'对方不必反复确认你会不会来。'),
    op('说明忙碌的时间，约一次短见面',{intimacy:4,energy:2},'这次安排不长，却很踏实。'),
    op('再次含糊答应，临时又改变安排',{intimacy:-12},'旧问题重新出现，这次更难被当作偶然。',{setFlags:{missed:true},followUp:follow('love-missed')}),
  ],{requiresFlags:['communicated'],notFlags:['missed']}),
  love('love-campus-aero','实验楼门口等你','你从实验楼出来时，{partner}已经等了一会儿。你们都知道这里的课程有时不会准点结束。',[
    op('及时说明进度，约在附近一起吃饭',{balance:-35,intimacy:5,energy:4},'实验报告还在，相处也没有消失。'),
    op('一起走回宿舍，分享今天的趣事',{intimacy:4,mood:4},'对方终于知道了你说的“实验又出了点小问题”具体是什么。'),
    op('又接着讨论作业，忽略了对方',{study:2,intimacy:-8},'作业多了一点思路，对方却觉得自己像实验楼的路灯。',{setFlags:{missed:true},followUp:follow('love-missed')}),
  ],{school:'aero'}),
  love('love-campus-normal','校园演出后的合影','演出结束，{partner}拉你去合影。台前热闹，后台的人正在收最后几根线。',[
    op('一起合影，再帮忙完成收尾',{intimacy:5,activity:1,energy:-4},'你们既留下照片，也留下一段后台的记忆。'),
    op('等对方忙完，再一起回去',{intimacy:4,mood:3},'你给对方留出了自己的事情，也留下了陪伴。'),
    op('说明自己累了，改约明天分享照片',{energy:7,intimacy:1},'你们没有为了合影勉强彼此。'),
  ],{school:'normal'}),
  love('love-campus-finance','恋爱也要做预算吗','{partner}开玩笑说，要不要给这次旅行列一张表。你发现自己真的开始计算交通与住宿。',[
    op('一起做预算，把最想做的事留下',{intimacy:5,study:1},'你们发现取舍也可以一起做。'),
    op('先安排一趟附近的小旅行',{balance:-180,intimacy:6,energy:-4},'这次旅程不远，却给忙碌生活换了一个背景。'),
    op('这次先不旅行，约定一个校园下午',{intimacy:3,mood:3},'你们把期待留到了更合适的时候。'),
  ],{school:'finance'}),
];
